big_projects_watch/urls.py
from django.conf.urls.defaults import patterns, url
from django.utils.translation import ugettext as _


handler404 = 'big_projects_watch.views.custom_404_view'

urlpatterns = patterns('',
    url(r'^$', 'big_projects_watch.views.index'),
    url(r'^404test/$', 'big_projects_watch.views.custom_404_view'),
    url(r'^%s$' % _('project_url'), 'big_projects_watch.views.project'),
    url(r'^%s(?P<project_part_id>\d+)/$' % _('project_parts_url'), 'big_projects_watch.views.project_part'),
    url(r'^%s$' % _('questions_url'), 'big_projects_watch.views.questions'),
    url(r'^%s$' % _('process_url'), 'big_projects_watch.views.process'),
    url(r'^%s(?P<event_id>\d+)/$' % _('events_url'), 'big_projects_watch.views.event'),
    url(r'^%s$' % _('participants_url'), 'big_projects_watch.views.participants'),
    url(r'^%s(?P<participant_id>\d+)/$' % _('participants_url'), 'big_projects_watch.views.participant'),
    url(r'^%s$' % _('documents_url'), 'big_projects_watch.views.documents'),
    url(r'^%s(?P<document_id>\d+)/$' % _('documents_url'), 'big_projects_watch.views.document'),
    url(r'^%s$' %  _('search_url'), 'big_projects_watch.views.search'),
    url(r'^%s$' % _('contact_url'), 'big_projects_watch.views.contact'),
    url(r'^%s$' % _('activate_document_relation_url'), 'big_projects_watch.views.activate_document_relation'),
    url(r'^%s$' % _('activate_comment_url'), 'big_projects_watch.views.activate_comment'),
)

big_projects_watch/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from big_projects_watch.models import ProjectPart, Participant, Event, Document


class DocContentRelationForm(forms.Form):
    RELATED_TO_TYPE_CHOICES = (
        ('projectpart', 'Projektbereich'),
        ('participant', 'Beteiligter'),
        ('event', 'Ereignis'),
        ('document', 'Dokument'),
    )
    document_id = forms.IntegerField(widget=forms.HiddenInput)
    
    help_text = _("The content on the page covers the following topic")
    related_to_type = forms.ChoiceField(choices=RELATED_TO_TYPE_CHOICES, help_text=help_text)
    
    related_to_id = forms.ModelChoiceField(queryset=Event.objects.all())
    related_to_id_projectpart = forms.ModelChoiceField(queryset=ProjectPart.objects.all())
    related_to_id_participant = forms.ModelChoiceField(queryset=Participant.objects.all())
    related_to_id_event = forms.ModelChoiceField(queryset=Event.objects.all())
    related_to_id_document = forms.ModelChoiceField(queryset=Document.objects.all())
    
    relation_type = forms.CharField(widget=forms.HiddenInput(), initial='C')
    
    help_text = _("Short sentence or a few tags about the content")
    description = forms.CharField(widget=forms.Textarea(attrs={'style':'width:500px;height:60px;'}), \
                    max_length=450, help_text=help_text)
    help_text = _("Page number in document (only the number, page number from PDF viewer)")
    # Using page_number instead of page here due to a strange form bug (initial display of a number)
    # which couldn't been localized
    page_number = forms.IntegerField(help_text=help_text)
    help_text = _("Additional comment (not publicly displayed)")
    comments = forms.CharField(widget=forms.Textarea(attrs={'style':'width:500px;height:60px;'}), \
                    max_length=450, required=False, help_text=help_text)
    

class DocAnnotationRelationForm(forms.Form):
    RELATED_TO_TYPE_CHOICES = (
        ('projectpart', 'Projektbereich'),
        ('participant', 'Beteiligter'),
        ('event', 'Ereignis'),
        ('document', 'Dokument'),
    )
    document_id = forms.IntegerField(widget=forms.HiddenInput)
    
    help_text = _("Annotation about the following topic")
    related_to_type = forms.ChoiceField(choices=RELATED_TO_TYPE_CHOICES, help_text=help_text)
    
    related_to_id = forms.ModelChoiceField(queryset=Event.objects.all())
    related_to_id_projectpart = forms.ModelChoiceField(queryset=ProjectPart.objects.all())
    related_to_id_participant = forms.ModelChoiceField(queryset=Participant.objects.all())
    related_to_id_event = forms.ModelChoiceField(queryset=Event.objects.all())
    related_to_id_document = forms.ModelChoiceField(queryset=Document.objects.all())
    
    relation_type = forms.CharField(widget=forms.HiddenInput(), initial='A')
    
    help_text = _("Annotation text")
    description = forms.CharField(widget=forms.Textarea(attrs={'style':'width:500px;height:60px;'}), \
                    max_length=450, help_text=help_text)
    help_text = _("Page number in document (only the number, page number from PDF viewer)")
    # Using page_number instead of page here due to a strange form bug (initial display of a number)
    # which couldn't been localized
    page_number = forms.IntegerField(help_text=help_text)
    help_text = _("Additional comment (not publicly displayed)")
    comments = forms.CharField(widget=forms.Textarea(attrs={'style':'width:500px;height:60px;'}), \
                    max_length=450, required=False, help_text=help_text)


class CommentForm(forms.Form):
    RELATED_TO_TYPE_CHOICES = (
        ('project_part', 'Projektbereich'),
        ('participant', 'Beteiligter'),
        ('event', 'Ereignis'),
        ('document', 'Dokument'),
    )
    content_type = forms.CharField(widget=forms.HiddenInput)
    object_id = forms.IntegerField(widget=forms.HiddenInput)
    
    help_text = _("Name")
    username = forms.CharField(widget=forms.TextInput(attrs={'style':'width:200px;'}), \
                            max_length=50, help_text=help_text)
    help_text = _("Comment")
    comment = forms.CharField(widget=forms.Textarea(attrs={'style':'width:500px;height:120px;'}), \
                    max_length=450, help_text=help_text)
    help_text = _("Page number in document (only the number, e.g. '5', '126', please take \
the page number from pdf viewer if different from page number inside the document), or empty \
if referring to the whole document.")
    # Using page_number instead of page here due to a strange form bug (initial display of a number)
    # which couldn't been localized
    page_number = forms.IntegerField(help_text=help_text, required=False)
    

big_projects_watch/templates/dialogs/comment.html
{% load i18n %}

{% if form_valid %}
  {% trans "Thank you for your comment. Your comment still needs to be activated." as confirm_text %}
  {% include "dialogs/generic_confirm.html" %}   
{% endif %}

<div class="modal hide fade" id="CommentModal">
  
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>{% trans "New Comment" %}</h3>
  </div>
  
  <form enctype="multipart/form-data" class="form-horizontal" action="." method="post">
  {% csrf_token %}
  <div class="modal-body">
    <script type="text/javascript">
      $(document).ready(function() {
        $('#CommentModal').modal({
          keyboard: false,
          {% if form.is_bound %}show: true{% else %}show: false{% endif %}
        })
      });
    </script>
    <p>
    {% for field in form.visible_fields %}
    {% if field.name != "page_number" or document %}
      <div class="control-group">
        {% for error in field.errors %}
          <div class="alert alert-error">{{ error }}</div>
        {% endfor %}
        <div>
          <div style="font-size:12px;margin-bottom:5px;{% if field.field.required %}font-weight: bold;{% endif %}">
            {{ field.help_text }}
          </div>
          {{ field }}
        </div>
      </div>
      {% endif %}
    {% endfor %}
    {% for field in form.hidden_fields %}
      {{ field }}
    {% endfor %}
    </p>
  </div>
  
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">{% trans "Close" %}</button>
    <input name="comment_form" type="submit" class="btn btn-primary" value="{% trans "Send comment" %}" />
  </div>
  </form>
  
</div>

big_projects_watch/templates/dialogs/doc_annotation_relation.html
{% load i18n %}

{% if form_valid %}
  {% trans "Thank you for your annotation. The annotation still needs to be activated." as confirm_text %}
  {% include "dialogs/generic_confirm.html" %}   
{% endif %}

<div class="modal hide fade" id="DocAnnotationRelationModal">
  
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>{% trans "Add annotation" %}</h3>
  </div>
  
  <form enctype="multipart/form-data" class="form-horizontal" action="." method="post">
  {% csrf_token %}
  <div class="modal-body">
    <script type="text/javascript">
      $(document).ready(function() {
        $('#DocAnnotationRelationModal').modal({
          keyboard: false,
          {% if form.is_bound %}show: true{% else %}show: false{% endif %}
        })
        remove_contenttype_model_selectbox_empty_choices('#DocAnnotationRelationModal', 'related_to');
        change_contenttype_selectbox_choices('#DocAnnotationRelationModal', 'related_to');
        
        $("#DocAnnotationRelationModal #id_related_to_type").change(function(){
          change_contenttype_selectbox_choices('#DocAnnotationRelationModal', 'related_to');
        });
      });
    </script>
    <p>
    {% for field in form.visible_fields %}
      <div class="control-group" style="
      {% if field.auto_id == "id_related_to_id_projectpart" or field.auto_id == "id_related_to_id_participant" or field.auto_id == "id_related_to_id_event" or field.auto_id == "id_related_to_id_document" %}display:none;{% endif %}">
        {% for error in field.errors %}
          <div class="alert alert-error">{{ error }}</div>
        {% endfor %}
        <div>
          <div style="font-size:12px;margin-bottom:5px;{% if field.field.required %}font-weight: bold;{% endif %}">
            {{ field.help_text }}
            
          </div>
          {{ field }}
        </div>
      </div>
    {% endfor %}
    {% for field in form.hidden_fields %}
      {{ field }}
    {% endfor %}
    </p>
  </div>
  
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">{% trans "Close" %}</button>
    <input name="doc_annotation_relation_form" type="submit" class="btn btn-primary" value="{% trans "Send annotation" %}" />
  </div>
  </form>
  
</div>

big_projects_watch/templates/dialogs/doc_content_relation.html
{% load i18n %}

{% if form_valid %}
  {% trans "Thank you for your supplement to the table of contents. Your supplement still needs to be activated." as confirm_text %}
  {% include "dialogs/generic_confirm.html" %}   
{% endif %}

<div class="modal hide fade" id="DocContentRelationModal">
  
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>{% trans "Supplement table of contents" %}</h3>
  </div>
  
  <form enctype="multipart/form-data" class="form-horizontal" action="." method="post">
  {% csrf_token %}
  <div class="modal-body">
    <script type="text/javascript">
      $(document).ready(function() {
        $('#DocContentRelationModal').modal({
          keyboard: false,
          {% if form.is_bound %}show: true{% else %}show: false{% endif %}
        })
        remove_contenttype_model_selectbox_empty_choices('#DocContentRelationModal', 'related_to');
        change_contenttype_selectbox_choices('#DocContentRelationModal', 'related_to');
        
        $("#DocContentRelationModal #id_related_to_type").change(function(){
          change_contenttype_selectbox_choices('#DocContentRelationModal', 'related_to');
        });
      });
    </script>
    <p>
    {% for field in form.visible_fields %}
      <div class="control-group" style="
      {% if field.auto_id == "id_related_to_id_projectpart" or field.auto_id == "id_related_to_id_participant" or field.auto_id == "id_related_to_id_event" or field.auto_id == "id_related_to_id_document" %}display:none;{% endif %}">
        {% for error in field.errors %}
          <div class="alert alert-error">{{ error }}</div>
        {% endfor %}
        <div>
          <div style="font-size:12px;margin-bottom:5px;{% if field.field.required %}font-weight: bold;{% endif %}">
            {{ field.help_text }}
            
          </div>
          {{ field }}
        </div>
      </div>
    {% endfor %}
    {% for field in form.hidden_fields %}
      {{ field }}
    {% endfor %}
    </p>
  </div>
  
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">{% trans "Close" %}</button>
    <input name="doc_content_relation_form" type="submit" class="btn btn-primary" value="{% trans "Send supplement" %}" />
  </div>
  </form>
  
</div>

big_projects_watch/templates/dialogs/document_relation.html
{% load i18n %}

{% if form_valid %}
  {% trans "Thank you for your relation proposal. Your proposal still needs to be activated." as confirm_text %}
  {% include "dialogs/generic_confirm.html" %}   
{% endif %}

<div class="modal hide fade" id="RelationModal">
  
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>{% trans "Propose Document Relation" %}</h3>
  </div>
  
  <form enctype="multipart/form-data" class="form-horizontal" action="." method="post">
  {% csrf_token %}
  <div class="modal-body">
    <script type="text/javascript">
      $(document).ready(function() {
        $('#RelationModal').modal({
          keyboard: false,
          {% if form.is_bound %}show: true{% else %}show: false{% endif %}
        })
        remove_contenttype_model_selectbox_empty_choices('related_to');
        change_contenttype_selectbox_choices('related_to');
        
        $("#id_related_to_type").change(function(){
          change_contenttype_selectbox_choices('related_to');
        });
      });
    </script>
    <p>
    {% for field in form.visible_fields %}
      <div class="control-group" style="
      {% if field.auto_id == "id_related_to_id_projectpart" or field.auto_id == "id_related_to_id_participant" or field.auto_id == "id_related_to_id_event" or field.auto_id == "id_related_to_id_document" %}display:none;{% endif %}">
        {% for error in field.errors %}
          <div class="alert alert-error">{{ error }}</div>
        {% endfor %}
        <div>
          <div style="font-size:12px;margin-bottom:5px;{% if field.field.required %}font-weight: bold;{% endif %}">
            {{ field.help_text }}
            
          </div>
          {{ field }}
        </div>
      </div>
    {% endfor %}
    {% for field in form.hidden_fields %}
      {{ field }}
    {% endfor %}
    </p>
  </div>
  
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">{% trans "Close" %}</button>
    <input name="document_relation_form" type="submit" class="btn btn-primary" value="{% trans "Send proposal" %}" />
  </div>
  </form>
  
</div>

big_projects_watch/templates/dialogs/generic_confirm.html
{% load i18n %}

<div class="modal hide fade" id="genericConfirm">
  <div class="modal-body">
    <p>{{ confirm_text }}</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">{% trans "Close" %}</button>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('#genericConfirm').modal({
      keyboard: false,
      show: true
    })
  });
</script>