big_projects_watch/urls.py
from django.conf.urls.defaults import patterns, url
from django.utils.translation import ugettext as _


handler404 = 'big_projects_watch.views.custom_404_view'

urlpatterns = patterns('',
    url(r'^$', 'big_projects_watch.views.index'),
    url(r'^404test/$', 'big_projects_watch.views.custom_404_view'),
    url(r'^%s$' % _('project_url'), 'big_projects_watch.views.project'),
    url(r'^%s(?P<project_part_id>\d+)/$' % _('project_parts_url'), 'big_projects_watch.views.project_part'),
    url(r'^%s$' % _('questions_url'), 'big_projects_watch.views.questions'),
    url(r'^%s$' % _('process_url'), 'big_projects_watch.views.process'),
    url(r'^%s(?P<event_id>\d+)/$' % _('events_url'), 'big_projects_watch.views.event'),
    url(r'^%s$' % _('participants_url'), 'big_projects_watch.views.participants'),
    url(r'^%s(?P<participant_id>\d+)/$' % _('participants_url'), 'big_projects_watch.views.participant'),
    url(r'^%s$' % _('documents_url'), 'big_projects_watch.views.documents'),
    url(r'^%s(?P<document_id>\d+)/$' % _('documents_url'), 'big_projects_watch.views.document'),
    url(r'^%s$' %  _('search_url'), 'big_projects_watch.views.search'),
    url(r'^%s$' % _('contact_url'), 'big_projects_watch.views.contact'),
    url(r'^%s$' % _('activate_document_relation_url'), 'big_projects_watch.views.activate_document_relation'),
    url(r'^%s$' % _('activate_comment_url'), 'big_projects_watch.views.activate_comment'),
)

big_projects_watch/models.py
# coding=UTF-8
import os
import shutil
import subprocess
from datetime import datetime

from django.db.models.signals import post_save, pre_delete
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.db import models
from django.utils.translation import ugettext, ugettext_lazy as _
from big_projects_watch.doc_scanner import DocScanner



class UserProfile(models.Model):
    user = models.OneToOneField(User)
    receive_new_document_relation_emails = models.BooleanField(default=True)
    receive_new_comment_emails = models.BooleanField(default=True)


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)


class Image(models.Model):
    title = models.CharField(max_length=250)
    image = models.ImageField(upload_to='images')
    help_text = _("Short linked html attribution snippet to the original image source or \
alternatively something like 'Own image'.")
    attribution_html = models.CharField(max_length=250, help_text=help_text)
    
    def __unicode__(self):
        return self.title
    
    class Meta:
        ordering = ['title',]


class SiteConfig(models.Model):
    help_text = _("Main title, shown in the header navi.")
    default = _("Project Website Title")
    title = models.CharField(max_length=250, help_text=help_text, default=default)
    help_text = _("Color for the page title (Format: '#990000').")
    title_color = models.CharField(max_length=7, help_text=help_text, default='#990000')
    help_text = _("Subtitle of the page.")
    default = _("Project Website Subtitle")
    sub_title = models.CharField(max_length=250, help_text=help_text, default=default)
    help_text = _("Color for the page subtitle (Format: '#990000').")
    sub_title_color = models.CharField(max_length=7, help_text=help_text, default='#444444')
    help_text = _("Short intro text to describe your page, not too long, use about text for detailed information.")
    default = _("This is a project watch website.")
    intro_text = models.TextField(help_text=help_text, default=default)
    help_text = _("Optional header image shown at the end of intro box on first page (Width: 450px \
Height: your choice, something around 175px is a good fit).")
    header_image = models.ForeignKey(Image, help_text=help_text, blank=True, null=True)
    help_text = _("Background color for the header (Format: '#990000').")
    header_bg_color = models.CharField(max_length=7, help_text=help_text, default='#EEEEEE')
    help_text = _("Color of the navi links (Format: '#990000').")
    navi_link_color = models.CharField(max_length=7, help_text=help_text, default='#FFFFFF')
    help_text = _("Background color for the navigation (Format: '#990000').")
    navi_bg_color = models.CharField(max_length=7, help_text=help_text, default='#333333')
    help_text = _("Background color to mark important elements on various parts of the site, \
font color will be white, so use something slightly darker.")
    important_bg_color = models.CharField(max_length=7, help_text=help_text, default='#990000')
    help_text = _("Short intro text about this site, what is the purpose, who is running it.")
    desc_about = models.TextField(help_text=help_text)
    help_text = _("Some html text you want to use in the footer of the page, you can e.g. \
provide a link to your email adress or associated social media sites.")
    footer_html = models.TextField(help_text=help_text, default=_("Footer HTML Default"))
    help_text = _("Html to be displayed on the contact page, provide at least an adress there \
and some contact information.")
    contact_html = models.TextField(help_text=help_text, default=_("Contact HTML Default"))
    comments = models.TextField(blank=True)
    
    def __unicode__(self):
        return self.title


class WebSource(models.Model):
    title = models.CharField(max_length=250)
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = generic.GenericForeignKey("content_type", "object_id")
    order = models.IntegerField(blank=True, null=True)
    url = models.URLField()
    date = models.DateField(blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __unicode__(self):
        return self.title
    
    class Meta:
        ordering = ['order']


class Participant(models.Model):
    PARTICIPANT_TYPE_CHOICES = (
        ('AD', _('Administration')),
        ('PO', _('Politics / Party / Parliament')),
        ('CI', _('Citizens')),
        ('CO', _('Company')),
        ('SE', _('Miscellaneous')),
    )
    PARTICIPANT_TYPE_CHOICES_ICONS = {
        'AD': 'icon-group',
        'PO': 'icon-group',
        'CI': 'icon-group',
        'CO': 'icon-group',
        'SE': 'icon-group',
    }
    help_text  = _("Person, group or institution acting in some way in the context of the project or being affected by the process or the result of the project execution.")
    name = models.CharField(max_length=250, help_text=help_text)
    participant_type = models.CharField(max_length=2, choices=PARTICIPANT_TYPE_CHOICES)
    help_text = _("Role/tasks as well as interests/goals of the participant regarding the project.")
    description = models.TextField(help_text=help_text)
    web_sources = generic.GenericRelation(WebSource)
    document_relations = generic.GenericRelation('DocumentRelation')
    user_comments = generic.GenericRelation('Comment')
    comments = models.TextField(blank=True)
    
    def __unicode__(self):
        return self.name
    
    def get_absolute_url(self):
        return "/" + ugettext("participants_url") + unicode(self.id) + "/"
    
    def get_participant_type_icon(self):
        return self.PARTICIPANT_TYPE_CHOICES_ICONS[self.participant_type]
    
    class Meta:
        ordering = ['name',]


class Project(models.Model):
    help_text = _("Name of the project.")
    name = models.CharField(max_length=250, help_text=help_text)
    responsible_participants = models.ManyToManyField(Participant, related_name="responsible_for_project")
    former_responsible_participants = models.ManyToManyField(Participant, related_name="formerly_responsible_for_project")
    help_text = _("General description of the project, what is it about, what is being done?")
    desc_project = models.TextField(help_text=help_text)
    help_text = _("What are the important parts of the project?")
    desc_project_parts = models.TextField(help_text=help_text)
    help_text = _("What questions regarding the project should be answered?")
    desc_questions = models.TextField(help_text=help_text)
    help_text = _("Who has initiated the project, what societal groups are involved?")
    desc_participants = models.TextField(help_text=help_text)
    help_text = _("What goals does the project target, what conditions should be met?")
    desc_goal_groups = models.TextField(help_text=help_text)
    help_text = _("What is the general process of the project development?")
    desc_process = models.TextField(help_text=help_text)
    help_text = _("What project documents are collected/provided?")
    desc_documents = models.TextField(help_text=help_text)
    web_sources = generic.GenericRelation(WebSource)
    comments = models.TextField(blank=True)
    
    def __unicode__(self):
        return self.name    


class ProjectPart(models.Model):
    help_text = _("Structural parts of the project being stable over time.")
    name = models.CharField(max_length=250, help_text=help_text)
    help_text = _("Use integer numbers for ordering (e.g. '100', '200', '300').")
    order = models.IntegerField(help_text=help_text, blank=True, null=True)
    help_text = _("Website (if existant).")
    description = models.TextField(help_text=help_text)
    web_sources = generic.GenericRelation(WebSource)
    document_relations = generic.GenericRelation('DocumentRelation')
    user_comments = generic.GenericRelation('Comment')
    comments = models.TextField(blank=True)

    def __unicode__(self):
        return self.name
    
    def get_absolute_url(self):
        return "/" + ugettext("project_parts_url") + unicode(self.id) + "/"
    
    class Meta:
        ordering = ['order',]


class Event(models.Model):
    EVENT_TYPE_CHOICES = (
        ('ME', _('Meeting / Gathering / Session')),
        ('IN', _('New Information / Decision / Statement')),
        ('MI', _('Project Progress / Execution / Milestone')),
        ('CI', _('Action by Civil Society')),
        ('UE', _('Unplanned Event')),
        ('SE', _('Miscellaneous')),
    )
    EVENT_TYPE_CHOICES_ICONS = {
        'ME': 'icon-calendar',
        'IN': 'icon-info-sign',
        'MI': 'icon-wrench',
        'CI': 'icon-bullhorn',
        'UE': 'icon-bolt',
        'SE': 'icon-asterisk',
    }
    title = models.CharField(max_length=250)
    event_type = models.CharField(max_length=2, choices=EVENT_TYPE_CHOICES)
    help_text = _("Event being of central importance for the project.")
    important = models.BooleanField(help_text=help_text)
    description = models.TextField()
    date = models.DateField()
    participants = models.ManyToManyField(Participant, related_name="related_events", blank=True, null=True)
    project_parts = models.ManyToManyField(ProjectPart, related_name="related_events", blank=True, null=True)
    web_sources = generic.GenericRelation(WebSource)
    document_relations = generic.GenericRelation('DocumentRelation')
    user_comments = generic.GenericRelation('Comment')
    comments = models.TextField(blank=True)
    
    def __unicode__(self):
        return self.title + ", " + datetime.strftime(self.date, '%d.%m.%Y') 
    
    def get_absolute_url(self):
        return "/" + ugettext("events_url") + unicode(self.id) + "/"
    

big_projects_watch/templates/base.html
{% load i18n %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ site_config.title }}{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="/static/css/lib/bootstrap.min.css" type="text/css">
  <link rel="stylesheet" href="/static/css/lib/font-awesome.css" type="text/css" />
  <link rel="stylesheet" href="/static/css/layout.css" type="text/css" />
  <link rel="shortcut icon" href="/static/favicon.ico" type="image/ico" />
  <meta name="robots" content="index, follow">
  <style type="text/css">
    <!--
    #navi a {
      color: {{ site_config.navi_link_color }};
    }
    @media (max-width: 767px) {
      #content .modal.fade.in {
        top: 5%;
      }
    }
    
    #text-layer > div {
      color: transparent;
      position: absolute;
    }
    
    .highlight {
      background-color:rgba(200, 255, 0, 0.2);
    }

    
    -->
  </style>
  <script src="/static/js/lib/jquery-1.8.1.min.js" type="text/javascript"></script>
  <script src="/static/js/lib/bootstrap.min.js" type="text/javascript"></script>
  <link rel="stylesheet" href="/static/css/lib/bootstrap-responsive.min.css" type="text/css" /> 
  <script src="/static/js/custom.js" type="text/javascript"></script>
</head>
<body>

<div class="container">

<div class="navbar" style="margin-bottom: 0px;">
  <div class="navbar-inner">
    <div class="container">

      <a class="brand" href="/" style="color:{{ site_config.title_color }};font-weight:bold;">{{ site_config.title }}  </a>
      <ul class="nav">
        <li><a href="/"><i class="icon-home"></i> Home</a></li>
        <li><a href="/{% trans "project_url" %}"><i class="icon-cogs"></i> {% trans "Project" %}</a></li>
        <li><a href="/{% trans "questions_url" %}"><i class="icon-cogs"></i> {% trans "Questions" %}</a></li>
        <li><a href="/{% trans "participants_url" %}"><i class="icon-group"></i> {% trans "Participants" %}</a></li>
        <li><a href="/{% trans "process_url" %}"><i class="icon-time"></i> {% trans "Process" %}</a></li>
        <li><a href="/{% trans "documents_url" %}"><i class="icon-inbox"></i> {% trans "Dokumente" %}</a></li>
        
      </ul>
      {% if site_config.with_public_docs %}
        <form class="navbar-search pull-right" action="/{% trans "search_url" %}" method="GET">
          <input type="text" class="search-query" name="q" value="{{ request.GET.q }}" placeholder="{% trans "Search" %}" style="width:180px;">
        </form>
      {% endif %}
    </div>
  </div>
  
</div>

<div class="row" id="content">

{% block content %}
{% endblock %}

</div>
<div class="row">
  <div class="span12" id="footer">
    <div class="row">
      <div class="span6">{% autoescape off %}{{ site_config.footer_html }}{% endautoescape %}</div>
      <div class="span6" style="text-align: right;">
        <a href="https://github.com/holgerd77/django-big-projects-watch" target="_blank">Source Code (GitHub)</a> | 
        <i class="icon-pushpin"></i> <a href="/{% trans "contact_url" %}">{% trans "Contact" %}</a>
      </div>    
    </div>
  </div>
  
</div>

</div>

</body>
</html>

big_projects_watch/templates/config_prerequisits.html
{% load i18n %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style type="text/css">
    <!--
    body {
      padding: 0px;
      margin: 0px;
      font-family: Arial, Helvetica, sans-serif;
    }
    #container {
      width: 600px;
      position: absolute;
      left: 50%;
      margin: 40px 0px 40px -300px;
      padding: 20px;
      border: 1px solid #e0e0e0;
    }
    #header {
      font-size: 20px;
      font-weight: bold;
      margin-bottom: 30px;
    }
    #content {
      font-size: 14px;
    }
    ul { padding-left: 16px;}
    li {
      margin: 20px 0px 20px 0px;
    }
    -->
  </style>
</head>
<body>
  <div id="container">
  <div id="header">
    {% trans "For the site to work the following configuration steps are necessary:"%}
  </div>
  
  <div id="content">
    <ul>
      {% for cp in missing_cps %}
      <li>{{ cp }}</li>
      {% endfor %}
    </ul>
  </div>
  
  </div>
</body>

big_projects_watch/templates/contact.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %} - {% trans "Contact" %}{% endblock %}

{% block content %}


<div class="span6">
  {% trans "Contact" as sh_title %}
  {% with sh_title=sh_title sh_icon="icon-pushpin" sh_url_title="" %}
    {% include "layout_elements/section_header.html" %}
  {% endwith %}
  
  <div class="section">
    <div class="info_box">
      <div class="info_box_content ib_text">
        {% autoescape off %}
          {{ site_config.contact_html|linebreaksbr }}  
        {% endautoescape %}
      </div>
    </div>
  </div>

  {% trans "Disclaimer" as sh_title %}
  {% with sh_title=sh_title sh_icon="icon-warning-sign" sh_url_title="" %}
    {% include "layout_elements/section_header.html" %}
  {% endwith %}
  
  <div class="section">
    <div class="info_box ib_text">
      <div class="info_box_content">
        {% trans "disclaimer_text" %}
      </div>
    </div>
  </div>

</div>

<div class="span6">

  {% trans "Credits" as sh_title %}
  {% with sh_title=sh_title sh_icon="icon-heart" sh_url_title="" %}
    {% include "layout_elements/section_header.html" %}
  {% endwith %}
  
  <div class="section">
    <div class="info_box">
      <div class="info_box_content ib_text">
        {% trans "credits_opensource_text" %}
        
        <ul style="margin-top: 10px;">
          <li>
            <a href="http://djangoproject.com" target="_blank">Django (Web Framework)</a>
          </li>
          <li>
            <a href="http://twitter.github.com/bootstrap/index.html" target="_blank">Twitter Bootstrap</a>
          </li>
          <li>
            <a href="http://fortawesome.github.com/Font-Awesome/" target="_blank">Font Awesome (Iconic Font Set)</a>
          </li>
          <li>
            <a href="https://github.com/Piratenfraktion-Berlin/PublicDocs" target="_blank">PublicDocs (PDF web viewer)</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  
  {% trans "Pictures" as sh_title %}
  {% with sh_title=sh_title sh_icon="icon-picture" sh_url_title="" %}
    {% include "layout_elements/section_header.html" %}
  {% endwith %}
  
  <div class="section">
    <div class="info_box">
      <div class="info_box_content ib_text">   
        <div style="margin-bottom: 10px;">
        {% trans "credits_pictures_text" %}
        </div>
        
        <table class="classic">
          {% for image in image_list %}
          <tr>
            <td>{{ image.title }}</td>
            <td>
              {% autoescape off %}
                {{ image.attribution_html }}
              {% endautoescape %}
            </td>
          </tr>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>
  
</div>

{% endblock %}

big_projects_watch/templates/document.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %} - {{ document }}{% endblock %}

{% block content %}


<div class="span8">
  {% trans "Document" as sh_title %}
  {% with sh_title=sh_title sh_icon="icon-inbox" sh_url_title="" %}
    {% include "layout_elements/section_header.html" %}
  {% endwith %}
  
  <div class="section">
    
    <div class="info_box" style="background-color: #f9f9f9;padding: 15px;">
      <div class="info_box_header">
        {{ document.title }}
      </div>
      <div class="info_box_content">
        <p style="font-size:12px;">
          {{ document.date }}
        </p>
        <p style="font-size:12px;font-weight:bold;">
          Download: <a href="/media/{{ document.document }}" target="_blank">{{ document.get_document_name }}</a>
        </p>
        <p>
          {{ document.description }}
        </p>
        
        {% with participant_list=document.participants.all %}
        {% if participant_list %}
          <p style="font-size:12px;">
            {% trans "Participants" %}:<br>
            {% for p in participant_list %}
              <a href="{{ p.get_absolute_url}}">{{ p }}</a><br>
            {% endfor %}
          </p>
        {% endif %}
        {% endwith %}
        {% with project_part_list=document.project_parts.all %}
        {% if project_part_list %}
          <p style="font-size:12px;">
            {% trans "Project Parts" %}:<br>
            {% for pp in project_part_list %}
              <a href="{{ pp.get_absolute_url}}">{{ pp }}</a><br>
            {% endfor %}
          </p>
        {% endif %}
        {% endwith %}
        {% with event_list=document.events.all %}
        {% if event_list %}
          <p style="font-size:12px;">
            {% trans "Events" %}:<br>
            {% for e in event_list %}
              <a href="{{ e.get_absolute_url}}">{{ e }}</a><br>
            {% endfor %}
          </p>
        {% endif %}
        {% endwith %}
        
      </div>
    </div>
    
  </div>
  
  
  {% if site_config.with_public_docs %}
    {% if site_config.use_pdfjs_viewer %}
    {% include "info_box/pdfjs_doc.html" %}
    {% else%}
      {% if document.pdf_images_generated %}
        {% include "info_box/publicdocs_doc.html" %}
      {% else %}
      <div class="alert alert-warn">
        {% trans "This document was just uploaded and is processed for presentation right now. This procedure can take a few minutes." %}
      </div>
      {% endif %}
    {% endif %}
  {% endif %}
 
  {% trans "Comments" as sh_title %}
  {% trans "New Comment" as sh_url_title %}
  {% with sh_title=sh_title sh_icon="icon-comments" sh_url_title=sh_url_title sh_url="#CommentModal" modal_url="yes" %}
    {% include "layout_elements/section_header.html" %}
  {% endwith %}
  {% with form=comment_form form_valid=comment_form_valid %}
  {% include "dialogs/comment.html" %}
  {% endwith %}
  
  {% include "info_box/comments.html" %}
 
</div>

<div class="span4">
  {% if site_config.browser = 'MSIE' %}
    <div class="alert alert-error">
      {% trans "The Internet Explorer is supporting only a basic version of the pdf viewer. Please use one of the following browsers for full functionality: Firefox, Chrome, Safari, Opera" %}
    </div>
  {% endif %}
  
  <div class="alert alert-info">
    {% trans "If different page numbers are referring to the declaration in the PDF viewer and not the declaration inside the document itself."%}
  </div>
  {% trans "Document Relations" as sh_title %}
  {% trans "Vorschlagen" as sh_url_title %}
  {% with sh_title=sh_title sh_icon="icon-inbox" sh_url_title=sh_url_title sh_url="#RelationModal" modal_url="yes" %}
    {% include "layout_elements/section_header.html" %}
  {% endwith %}
  
  {% with show_document="" show_related_to="yes" %}
    {% include "info_box/document_relations.html" %}
  {% endwith %}
  {% with form=document_relation_form form_valid=document_relation_form_valid %}
    {% include "dialogs/document_relation.html" %}
  {% endwith %}
  
</div>

{% endblock %}

big_projects_watch/templates/documents.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %} - {% trans "Documents" %}{% endblock %}

{% block content %}


<div class="span6">
  {% trans "Documents" as sh_title %}
  {% with sh_title=sh_title sh_icon="icon-inbox" sh_url_title="" %}
    {% include "layout_elements/section_header.html" %}
  {% endwith %}
  
  <div class="section">
    {% with ib_content=project.desc_documents %}
    {% include "info_box/generic.html"%}
    {% endwith %}
    <br>
    {% include "info_box/documents.html" %}
  </div>
  
</div>

<div class="span6">

  {% trans "New Document Relations" as sh_title %}
  {% with sh_title=sh_title sh_icon="icon-inbox" %}
    {% include "layout_elements/section_header.html" %}
  {% endwith %}
  
  {% with show_document="yes" show_related_to="yes" document_relation_list=latest_document_relation_list %}
    {% include "info_box/document_relations.html" %}
  {% endwith %}

  {% trans "New Comments" as sh_title %}
  {% with sh_title=sh_title sh_icon="icon-comments" sh_url_title="" %}
    {% include "layout_elements/section_header.html" %}
  {% endwith %}
  
  {% with show_commented_object="yes" %}
  {% include "info_box/comments.html" %}
  {% endwith %} 
  
</div>

{% endblock %}

big_projects_watch/templates/participant.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %} - {{ participant }}{% endblock %}

{% block content %}


<div class="span6">
  {% trans "Participant" as sh_title %}
  {% with sh_title=sh_title sh_icon="icon-group" sh_url_title="" %}
    {% include "layout_elements/section_header.html" %}
  {% endwith %}
  
  <div class="section">
    
    <div class="info_box" style="background-color: #f9f9f9;padding: 15px;">
      <div class="info_box_header" style="font-size:16px;">
        {{ participant.name }}
      </div>
      <div class="info_box_content">
        <p style="font-size:12px;">
          {% trans "Type" %}: {{ participant.get_participant_type_display }}
        </p>
        <p>
          {{ participant.description }}
        </p>
      </div>
    </div>
    
  </div>
  
  {% with web_source_list=participant.web_sources.all %}
  {% include "info_box/web_sources.html" %}
  {% endwith %}
  
  {% trans "Events" as sh_title %}
  {% with sh_title=sh_title sh_icon="icon-time" sh_url_title="" %}
    {% include "layout_elements/section_header.html" %}
  {% endwith %}
  
  {% with event_list=participant.related_events.all %}
    {% include "info_box/events.html" %}
  {% endwith %}
  
  
  {% trans "Comments" as sh_title %}
  {% trans "New Comment" as sh_url_title %}
  {% with sh_title=sh_title sh_icon="icon-comments" sh_url_title=sh_url_title sh_url="#CommentModal" modal_url="yes" %}
    {% include "layout_elements/section_header.html" %}
  {% endwith %}
  {% with form=comment_form form_valid=comment_form_valid %}
  {% include "dialogs/comment.html" %}
  {% endwith %}
  
  {% include "info_box/comments.html" %}
 
</div>

<div class="span6">
  
  {% trans "Questions" as sh_title %}
  {% with sh_title=sh_title sh_icon="icon-question-sign" sh_url_title="" %}
    {% include "layout_elements/section_header.html" %}
  {% endwith %}
  
  {% with question_list=participant.related_questions.all %}
    {% include "info_box/questions.html" %}
  {% endwith %}
  
  {% trans "Documents" as sh_title %}
  {% with sh_title=sh_title sh_icon="icon-inbox" sh_url_title="" %}
    {% include "layout_elements/section_header.html" %}
  {% endwith %}
    
  {% include "info_box/documents.html" %}

  
  {% trans "Document Relations" as sh_title %}
  {% with sh_title=sh_title sh_icon="icon-inbox" sh_url_title="" %}
    {% include "layout_elements/section_header.html" %}
  {% endwith %}
  
  {% with show_document="yes" %}
    {% include "info_box/document_relations.html" %}
  {% endwith %}
  
</div>

{% endblock %}

big_projects_watch/templates/process.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %} - {% trans "Process" %}{% endblock %}

{% block content %}


<div class="span6">

  {% trans "Process" as sh_title %}
  {% with sh_title=sh_title sh_icon="icon-time" sh_url_title="" %}
    {% include "layout_elements/section_header.html" %}
  {% endwith %}
  
  <div class="section">
    
    {% with ib_content=project.desc_process %}
    {% include "info_box/generic.html"%}
    {% endwith %}
  
  </div>
  
  {% trans "Events" as sh_title %}
  {% with sh_title=sh_title sh_icon="icon-time" %}
    {% include "layout_elements/section_header.html" %}
  {% endwith %}
  
  <div class="section">
    
    <div class="info_box">
      <div class="info_box_content">
        
            {% include "info_box/events.html" %}
        
      </div>
    </div>
    
  </div>
  
</div>

<div class="span6">

  {% trans "New Comments" as sh_title %}
  {% with sh_title=sh_title sh_icon="icon-comments" sh_url_title="" %}
    {% include "layout_elements/section_header.html" %}
  {% endwith %}
  
  {% with show_commented_object="yes" %}
  {% include "info_box/comments.html" %}
  {% endwith %}  
  
</div>

{% endblock %}